# Generated by Django 4.2.7 on 2024-03-09 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm_messages", "0007_alter_botmessages_message_telegram_id"),
        (
            "reports",
            "0003_alter_report_ambassador_alter_report_placement_and_more",
        ),
        ("merches", "0005_alter_ambassadorrequest_ambassador_and_more"),
        ("ambassador", "0008_alter_ambassador_address_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "default_ambassador_status",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ambassador.ambassadorstatus",
                    ),
                ),
                (
                    "default_delivery_status",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="merches.deliverystatus",
                    ),
                ),
                (
                    "default_message_status",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_message_status",
                        to="crm_messages.messagestatus",
                    ),
                ),
                (
                    "default_message_type",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm_messages.messagetype",
                    ),
                ),
                (
                    "default_report_status",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.reportstatus",
                    ),
                ),
                (
                    "default_report_type",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.reporttype",
                    ),
                ),
                (
                    "delayed_sending_message_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delayed_sending_message_type",
                        to="crm_messages.messagestatus",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
    ]
