# Generated by Django 4.2.7 on 2024-02-25 20:16

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator
                ],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
