# Generated by Django 4.2.7 on 2024-02-25 13:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'index',
                    models.CharField(
                        help_text='Укажите шестизначный почтовый индекс.',
                        max_length=255,
                        verbose_name='Почтовый индекс',
                    ),
                ),
                (
                    'region',
                    models.CharField(
                        help_text='Введите название области или края.',
                        max_length=255,
                        verbose_name='Область',
                    ),
                ),
                (
                    'area',
                    models.CharField(
                        help_text='Заполните название района, округа или города.',
                        max_length=255,
                        verbose_name='Район',
                    ),
                ),
                (
                    'locality',
                    models.CharField(
                        help_text='Укажите название поселка, села, деревни или города.',
                        max_length=255,
                        verbose_name='Населенный пункт',
                    ),
                ),
                (
                    'street',
                    models.CharField(
                        help_text='Введите название улицы или проспекта.',
                        max_length=255,
                        verbose_name='Улица',
                    ),
                ),
                (
                    'house',
                    models.CharField(
                        help_text='Заполните номер дома.',
                        max_length=255,
                        verbose_name='Дом',
                    ),
                ),
                (
                    'building',
                    models.CharField(
                        blank=True,
                        help_text='Укажите номер корпуса (если есть).',
                        max_length=255,
                        verbose_name='Корпус',
                    ),
                ),
                (
                    'structure',
                    models.CharField(
                        blank=True,
                        help_text='Введите номер строения (если есть).',
                        max_length=255,
                        verbose_name='Строение',
                    ),
                ),
                (
                    'apartment',
                    models.CharField(
                        blank=True,
                        help_text='Заполните номер квартиры (если есть).',
                        max_length=255,
                        verbose_name='Квартира',
                    ),
                ),
                (
                    'address_confirmation_status',
                    models.CharField(
                        choices=[
                            ('pending', 'Ожидание подтверждения'),
                            ('confirmed', 'Подтвержден'),
                            ('cancel', 'Отклонен'),
                        ],
                        default='pending',
                        max_length=255,
                        verbose_name='Статус подтверждения адреса',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адрес доставки',
            },
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'merchandise_name',
                    models.CharField(max_length=255, verbose_name='Название мерча'),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name='Цена'
                    ),
                ),
                (
                    'intangible_attribute',
                    models.BooleanField(verbose_name='Признак нематериального мерча'),
                ),
            ],
            options={
                'verbose_name': 'Мерч',
                'verbose_name_plural': 'Мерч',
            },
        ),
        migrations.CreateModel(
            name='RequestAmbassador',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'ambassador',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='merches.ambassador',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заявки амбассадоров',
                'verbose_name_plural': 'Заявки амбассадоров',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('request_date', models.DateTimeField(verbose_name='Дата отправки')),
                (
                    'date_transfer_to_logist',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Дата передачи логистам'
                    ),
                ),
                (
                    'request_status',
                    models.CharField(
                        choices=[
                            ('pending', 'Ожидание подтверждения'),
                            ('confirmed', 'Подтвержден'),
                            ('cancel', 'Отклонен'),
                        ],
                        default='pending',
                        max_length=255,
                        verbose_name='Статус выполнения',
                    ),
                ),
                (
                    'ambassador',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='merches.requestambassador',
                    ),
                ),
                (
                    'delivery_address',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='merches.deliveryaddress',
                    ),
                ),
                (
                    'imerchandise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='merches.merch'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заявки на мерчи',
                'verbose_name_plural': 'Заявки на мерч',
            },
        ),
    ]
