# Generated by Django 4.2.7 on 2024-02-29 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("merches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchrequest",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AddField(
            model_name="merchrequest",
            name="merch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.merch",
                verbose_name="Мерч",
            ),
        ),
        migrations.AddField(
            model_name="merchrequest",
            name="request_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.delevirystatus",
                verbose_name="Статус выполнения",
            ),
        ),
        migrations.AddField(
            model_name="deliveryhistory",
            name="delivery_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.delevirystatus",
                verbose_name="Запрос на мерч",
            ),
        ),
        migrations.AddField(
            model_name="deliveryhistory",
            name="merch_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.merchrequest",
                verbose_name="Запрос на мерч",
            ),
        ),
        migrations.AddField(
            model_name="ambassadorrequest",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.ambassador",
            ),
        ),
        migrations.AddField(
            model_name="ambassadorrequest",
            name="merch_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.merchrequest",
            ),
        ),
    ]
