# Generated by Django 4.2.7 on 2024-02-25 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="requestambassador",
            options={
                "verbose_name": "Заявки амбассадоров на мерч",
                "verbose_name_plural": "Заявки амбассадоров на мерч",
            },
        ),
        migrations.RemoveField(
            model_name="request",
            name="imerchandise",
        ),
        migrations.AddField(
            model_name="request",
            name="merchandise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.merch",
            ),
        ),
        migrations.AddField(
            model_name="requestambassador",
            name="request_merch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.request",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.requestambassador",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="delivery_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.deliveryaddress",
            ),
        ),
        migrations.AlterField(
            model_name="requestambassador",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.ambassador",
            ),
        ),
        migrations.AlterField(
            model_name="requestambassador",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="address_confirmation_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.status",
                verbose_name="Статус подтверждения адреса",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="request_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.status",
                verbose_name="Статус выполнения",
            ),
        ),
    ]
