# Generated by Django 4.2.7 on 2024-02-28 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merches", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassadorrequest",
            name="merch_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.merchrequest",
            ),
        ),
        migrations.AlterField(
            model_name="delevirystatus",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="merch",
            name="available",
            field=models.BooleanField(
                default=True, verbose_name="Доступен мерч"
            ),
        ),
        migrations.AlterField(
            model_name="merchrequest",
            name="request_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.delevirystatus",
                verbose_name="Статус выполнения",
            ),
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
