# Generated by Django 4.2.7 on 2024-03-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merches", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliverystatus",
            old_name="delivery_status",
            new_name="status_name",
        ),
        migrations.AlterField(
            model_name="merch",
            name="intangible",
            field=models.BooleanField(
                default=False, verbose_name="Признак нематериального мерча"
            ),
        ),
        migrations.AlterField(
            model_name="merch",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
