# Generated by Django 4.2.7 on 2024-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merches", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassadorrequest",
            name="assignment_date",
            field=models.DateField(verbose_name="Дата создания запроса"),
        ),
        migrations.AlterField(
            model_name="deliveryhistory",
            name="assignment_date",
            field=models.DateField(verbose_name="Дата присвоения"),
        ),
    ]
