# Generated by Django 4.2.7 on 2024-02-26 17:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("merches", "0002_status_alter_requestambassador_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmbassadorRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignment_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата создания запроса"
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="merches.ambassador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявки амбассадоров на мерч",
                "verbose_name_plural": "Заявки амбассадоров на мерч",
            },
        ),
        migrations.CreateModel(
            name="DeleviryStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(max_length=100, unique=True),
                ),
                ("available", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Статус доставки",
                "verbose_name_plural": "Статус доставки",
            },
        ),
        migrations.CreateModel(
            name="DeliveryHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignment_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "delivery_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="merches.delevirystatus",
                        verbose_name="Запрос на мерч",
                    ),
                ),
            ],
            options={
                "verbose_name": "История доставок",
                "verbose_name_plural": "История доставок",
            },
        ),
        migrations.CreateModel(
            name="MerchRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявки на мерчи",
                "verbose_name_plural": "Заявки на мерч",
            },
        ),
        migrations.RemoveField(
            model_name="requestambassador",
            name="ambassador",
        ),
        migrations.RemoveField(
            model_name="requestambassador",
            name="request_merch",
        ),
        migrations.RenameField(
            model_name="deliveryaddress",
            old_name="area",
            new_name="district",
        ),
        migrations.RenameField(
            model_name="merch",
            old_name="merchandise_name",
            new_name="merch_name",
        ),
        migrations.RemoveField(
            model_name="deliveryaddress",
            name="address_confirmation_status",
        ),
        migrations.RemoveField(
            model_name="deliveryaddress",
            name="locality",
        ),
        migrations.RemoveField(
            model_name="deliveryaddress",
            name="structure",
        ),
        migrations.RemoveField(
            model_name="merch",
            name="intangible_attribute",
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Укажите страну",
                max_length=255,
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="is_confirmed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="settlement",
            field=models.CharField(
                blank=True,
                help_text="Укажите название поселка, села, деревни или города",
                max_length=255,
                verbose_name="Населенный пункт",
            ),
        ),
        migrations.AddField(
            model_name="merch",
            name="available",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Доступен мерч"
            ),
        ),
        migrations.AddField(
            model_name="merch",
            name="intangible",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Признак нематериального мерча",
            ),
        ),
        migrations.DeleteModel(
            name="Request",
        ),
        migrations.DeleteModel(
            name="RequestAmbassador",
        ),
        migrations.AddField(
            model_name="merchrequest",
            name="delivery_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.deliveryaddress",
                verbose_name="Адрес доставки",
            ),
        ),
        migrations.AddField(
            model_name="merchrequest",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AddField(
            model_name="merchrequest",
            name="merch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.merch",
                verbose_name="Мерч",
            ),
        ),
        migrations.AddField(
            model_name="merchrequest",
            name="request_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.status",
                verbose_name="Статус выполнения",
            ),
        ),
        migrations.AddField(
            model_name="deliveryhistory",
            name="merch_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.merchrequest",
                verbose_name="Запрос на мерч",
            ),
        ),
        migrations.AddField(
            model_name="ambassadorrequest",
            name="merch_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.merchrequest",
            ),
        ),
    ]
