# Generated by Django 4.2.7 on 2024-03-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "merches",
            "0003_rename_delivery_status_deliverystatus_status_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryaddress",
            name="country",
            field=models.CharField(
                help_text="Укажите страну",
                max_length=255,
                verbose_name="Страна",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="district",
            field=models.CharField(
                blank=True,
                help_text="Заполните название района, округа или города.",
                max_length=255,
                verbose_name="Район",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Введите название области или края.",
                max_length=255,
                verbose_name="Область",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="settlement",
            field=models.CharField(
                help_text="Укажите название поселка, села, деревни или города",
                max_length=255,
                verbose_name="Населенный пункт",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="street",
            field=models.CharField(
                blank=True,
                help_text="Введите название улицы или проспекта.",
                max_length=255,
                verbose_name="Улица",
            ),
        ),
    ]
