# Generated by Django 4.2.7 on 2024-03-05 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ambassador",
            "0004_alter_ambassador_manager_alter_ambassador_status_and_more",
        ),
        ("merches", "0004_alter_ambassadorrequest_ambassador_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassadorrequest",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="ambassador.ambassador",
            ),
        ),
        migrations.AlterField(
            model_name="ambassadorrequest",
            name="merch_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="merches.merchrequest",
            ),
        ),
    ]
