# Generated by Django 4.2.7 on 2024-02-25 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achieve",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "achieve_name",
                    models.CharField(max_length=255, verbose_name="Название ачивки"),
                ),
            ],
            options={
                "verbose_name": "Ачивки",
                "verbose_name_plural": "Ачивки",
            },
        ),
        migrations.CreateModel(
            name="AchieveAmbassador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignment_date_achieve",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата получения ачивки"
                    ),
                ),
                (
                    "id_achieve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.achieve",
                    ),
                ),
                (
                    "id_ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merches.ambassador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ачивки амбассадоров",
                "verbose_name_plural": "Ачивки амбассадоров",
            },
        ),
    ]
