# Generated by Django 4.2.7 on 2024-02-29 05:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achieve",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "achieve_name",
                    models.CharField(
                        max_length=255, verbose_name="Название ачивки"
                    ),
                ),
                ("available", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Ачивки",
                "verbose_name_plural": "Ачивки",
            },
        ),
        migrations.CreateModel(
            name="AmbassadorAchieve",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата получения ачивки"
                    ),
                ),
                (
                    "achieve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="achievements.achieve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ачивки амбассадоров",
                "verbose_name_plural": "Ачивки амбассадоров",
            },
        ),
    ]
