# Generated by Django 4.2.7 on 2024-02-25 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merches", "0002_status_alter_requestambassador_options_and_more"),
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achieveambassador",
            name="id_achieve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="achievements.achieve",
            ),
        ),
        migrations.AlterField(
            model_name="achieveambassador",
            name="id_ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.ambassador",
            ),
        ),
    ]
