# Generated by Django 4.2.7 on 2024-03-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("achievements", "0001_initial"),
        ("ambassador", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambassadorachieve",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ambassador.ambassador",
            ),
        ),
    ]
