# Generated by Django 4.2.7 on 2024-02-26 17:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "merches",
            "0003_ambassadorrequest_delevirystatus_deliveryhistory_and_more",
        ),
        ("achievements", "0002_alter_achieveambassador_id_achieve_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmbassadorAchieve",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата получения ачивки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ачивки амбассадоров",
                "verbose_name_plural": "Ачивки амбассадоров",
            },
        ),
        migrations.AddField(
            model_name="achieve",
            name="available",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="AchieveAmbassador",
        ),
        migrations.AddField(
            model_name="ambassadorachieve",
            name="achieve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="achievements.achieve",
            ),
        ),
        migrations.AddField(
            model_name="ambassadorachieve",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="merches.ambassador",
            ),
        ),
    ]
