# Generated by Django 4.2.7 on 2024-03-05 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ambassador", "0003_ambassadorgoal_own_version"),
        ("achievements", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassadorachieve",
            name="achieve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassador_achieve",
                to="achievements.achieve",
            ),
        ),
        migrations.AlterField(
            model_name="ambassadorachieve",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="achieves",
                to="ambassador.ambassador",
            ),
        ),
    ]
