# Generated by Django 4.2.7 on 2024-02-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achieve",
            name="achieve_name",
            field=models.CharField(
                max_length=50, verbose_name="Название ачивки"
            ),
        ),
        migrations.AlterField(
            model_name="achieve",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Доступна"),
        ),
    ]
