# Generated by Django 4.2.7 on 2024-03-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0004_alter_ambassadorachieve_achieve"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AmbassadorAchieve",
        ),
    ]
