version: "3.9"
name: "ya-amb-crm"
services:
  postgres:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - data_value:/var/lib/postgresql/data/

  frontend:
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
    image: asbest/am-crm-frontend:latest
    volumes:
      # - ../frontend/result_build:/app/result_build/
      - ../frontend/site:/app/result_build/

  django:
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - frontend
    volumes:
      - ../frontend/site/static:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx_prod.conf:/etc/nginx/conf.d/default.conf
      - media_value:/var/html/media/
      - ../frontend/site/build:/usr/share/nginx/html/
      - ../frontend/site/static:/var/html/static/
    depends_on:
      - django


volumes:
  data_value:
  media_value: