# Generated by Django 4.2.7 on 2024-02-29 05:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ambassador", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "message_text",
                    models.CharField(
                        max_length=250, verbose_name="Текст сообщения"
                    ),
                ),
                ("media_link", models.FileField(upload_to="")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата сообщения"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status_name",
                    models.CharField(
                        max_length=250, verbose_name="Наименование статуса"
                    ),
                ),
                ("available", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="MessageType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("type_name", models.CharField(max_length=250)),
                ("available", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="MessagePool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "send_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата"
                    ),
                ),
                (
                    "message_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm_messages.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "message_status",
                    models.ForeignKey(
                        max_length=50,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm_messages.messagestatus",
                        verbose_name="Статус сообщения",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="message_type_id",
            field=models.ForeignKey(
                max_length=50,
                on_delete=django.db.models.deletion.PROTECT,
                to="crm_messages.messagetype",
            ),
        ),
        migrations.CreateModel(
            name="BotMessages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("from_bot", models.BooleanField()),
                (
                    "sign_ai",
                    models.BooleanField(
                        verbose_name="Искусственный интеллект"
                    ),
                ),
                (
                    "ambassador_id",
                    models.ForeignKey(
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambassador.ambassador",
                        verbose_name="Амбасадор",
                    ),
                ),
            ],
        ),
    ]
