# Generated by Django 4.2.7 on 2024-02-29 19:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ambassador", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "message_text",
                    models.CharField(
                        max_length=250, verbose_name="Текст сообщения"
                    ),
                ),
                (
                    "media_link",
                    models.FileField(
                        null=True,
                        upload_to="messages/",
                        verbose_name="Медиа файл",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата сообщения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="MessageStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status_name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Наименование статуса",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=True, verbose_name="Доступность"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус сообщения",
                "verbose_name_plural": "Статусы сообщения",
            },
        ),
        migrations.CreateModel(
            name="MessageType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Тип сообщения",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=True, verbose_name="Доступность"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип сообщения",
                "verbose_name_plural": "Типы сообщения",
            },
        ),
        migrations.CreateModel(
            name="MessagePool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "send_date",
                    models.DateTimeField(
                        null=True, verbose_name="Когда отправить сообщение"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm_messages.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "message_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm_messages.messagestatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Служебное сообщение",
                "verbose_name_plural": "Служебные сообщения",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.ForeignKey(
                max_length=50,
                on_delete=django.db.models.deletion.PROTECT,
                to="crm_messages.messagetype",
            ),
        ),
        migrations.CreateModel(
            name="BotMessages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("from_bot", models.BooleanField()),
                (
                    "sign_ai",
                    models.BooleanField(
                        verbose_name="Искусственный интеллект"
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ambassador.ambassador",
                        verbose_name="Амбасcадор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение телеграм бота",
                "verbose_name_plural": "Сообщения телеграм бота",
            },
        ),
    ]
