# Generated by Django 4.2.7 on 2024-03-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_messages", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="media_link",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="messages/",
                verbose_name="Медиа файл",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="crm_messages.messagetype",
            ),
        ),
        migrations.AlterField(
            model_name="messagepool",
            name="send_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Когда отправить сообщение"
            ),
        ),
    ]
