# Generated by Django 4.2.7 on 2024-03-01 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "crm_messages",
            "0003_alter_message_media_link_alter_message_message_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="botmessages",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
    ]
