# Generated by Django 4.2.7 on 2024-03-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_messages", "0004_alter_botmessages_ambassador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmessages",
            name="message_telegram_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                verbose_name="Номер сообщения в телеграм",
            ),
        ),
        migrations.AddField(
            model_name="botmessages",
            name="reaction",
            field=models.IntegerField(
                choices=[(-1, "Дизлайк"), (0, ""), (1, "Лайк")],
                default=0,
                verbose_name="Реация на сообщение",
            ),
        ),
    ]
