# Generated by Django 4.2.7 on 2024-03-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "crm_messages",
            "0005_botmessages_message_telegram_id_botmessages_reaction",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="botmessages",
            name="reaction",
            field=models.IntegerField(
                choices=[(-1, "Дизлайк"), (0, "Нет реакции"), (1, "Лайк")],
                default=0,
                verbose_name="Реация на сообщение",
            ),
        ),
    ]
