# Generated by Django 4.2.7 on 2024-03-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_messages", "0006_alter_botmessages_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botmessages",
            name="message_telegram_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Номер сообщения в телеграм",
            ),
        ),
    ]
