# Generated by Django 4.2.7 on 2024-03-03 09:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ambassador", "0003_ambassadorgoal_own_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "program_name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Название программы обучения",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступна"),
                ),
            ],
            options={
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы",
            },
        ),
        migrations.CreateModel(
            name="AmbassadorProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ambassador.ambassador",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="program.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа амбассадоров",
                "verbose_name_plural": "Программы амбассадоров",
            },
        ),
    ]
