# Generated by Django 4.2.7 on 2024-03-05 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ambassador",
            "0004_alter_ambassador_manager_alter_ambassador_status_and_more",
        ),
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassadorprogram",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programs",
                to="ambassador.ambassador",
            ),
        ),
        migrations.AlterField(
            model_name="ambassadorprogram",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="program.program",
            ),
        ),
    ]
