# Generated by Django 4.2.7 on 2024-03-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0002_alter_ambassadorprogram_ambassador_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AmbassadorProgram",
        ),
    ]
