# Generated by Django 4.2.7 on 2024-02-29 05:44

import uuid

import django.db.models.deletion
from django.db import migrations, models

import reports.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ambassador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        max_length=100,
                        verbose_name="Площадка размещения контента",
                    ),
                ),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReportStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status_name", models.CharField(max_length=100)),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReportType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_name",
                    models.CharField(
                        max_length=100, verbose_name="Вид задания"
                    ),
                ),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID Отчета",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата отчета"
                    ),
                ),
                (
                    "content_link",
                    models.URLField(
                        help_text="Добавьте ссылку на контент",
                        verbose_name="Ссылка на контент",
                    ),
                ),
                (
                    "screen",
                    models.FileField(
                        default=None, null=True, upload_to="reports/screens/"
                    ),
                ),
                ("sign_junior", models.BooleanField()),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        validators=[reports.validators.validate_one_to_ten]
                    ),
                ),
                (
                    "ambassador_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.ambassador",
                    ),
                ),
                (
                    "placement_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.placement",
                    ),
                ),
                (
                    "report_status_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.reportstatus",
                    ),
                ),
                (
                    "report_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.reporttype",
                    ),
                ),
            ],
        ),
    ]
