# Generated by Django 4.2.7 on 2024-03-01 10:27

import django.db.models.deletion
from django.db import migrations, models

import reports.validators


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="grade",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[reports.validators.validate_one_to_ten]
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="reports.reportstatus",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="screen",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="reports/",
                verbose_name="Скриншот",
            ),
        ),
    ]
