# Generated by Django 4.2.7 on 2024-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_date",
            field=models.DateField(verbose_name="Дата отчета"),
        ),
    ]
