# Generated by Django 4.2.7 on 2024-02-29 05:44

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "achive_name",
                    models.CharField(max_length=50, verbose_name="Достижение"),
                ),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "activity_name",
                    models.CharField(
                        max_length=50, verbose_name="Вид деятельности"
                    ),
                ),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ambassador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "promocode",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Промокод"
                    ),
                ),
                (
                    "receipt_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "reminder_counter",
                    models.PositiveIntegerField(
                        blank=True, verbose_name="Счетчик напоминалок"
                    ),
                ),
                (
                    "adress_index",
                    models.CharField(max_length=10, verbose_name="Индекс"),
                ),
                (
                    "adress_country",
                    models.CharField(max_length=50, verbose_name="Страна"),
                ),
                (
                    "adress_region",
                    models.CharField(max_length=50, verbose_name="Регион"),
                ),
                (
                    "adress_district",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Район"
                    ),
                ),
                (
                    "adress_settlement",
                    models.CharField(
                        max_length=50, verbose_name="Населённый пункт"
                    ),
                ),
                (
                    "adress_street",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Улица"
                    ),
                ),
                (
                    "adress_house",
                    models.PositiveIntegerField(verbose_name="Дом"),
                ),
                (
                    "adress_building",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Корпус"
                    ),
                ),
                (
                    "adress_apartment",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Квартира"
                    ),
                ),
                (
                    "size_clothing",
                    models.CharField(
                        max_length=2, verbose_name="Размер одежды"
                    ),
                ),
                (
                    "size_choe",
                    models.PositiveIntegerField(verbose_name="Размер обуви"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=18,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                14, message="Минимум 14 символов"
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "note",
                    models.TextField(
                        blank=True, max_length=50, verbose_name="Заметка"
                    ),
                ),
                ("blog_link", models.URLField(verbose_name="Ссылка на блог")),
                (
                    "place_work",
                    models.CharField(
                        max_length=50, verbose_name="Место работы"
                    ),
                ),
                (
                    "specialty_work",
                    models.CharField(max_length=50, verbose_name="Должность"),
                ),
                (
                    "educational_institution",
                    models.CharField(
                        max_length=50, verbose_name="Учебное заведение"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Фамилия"),
                ),
                (
                    "middle_name",
                    models.CharField(max_length=50, verbose_name="Отчество"),
                ),
                (
                    "gender",
                    models.CharField(max_length=50, verbose_name="Пол"),
                ),
                ("birthday", models.DateField(verbose_name="Дата рождения")),
            ],
            options={
                "verbose_name": "Амбасадор",
                "verbose_name_plural": "Амбасадоры",
            },
        ),
        migrations.CreateModel(
            name="AmbassadorStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status_name",
                    models.CharField(
                        max_length=50, verbose_name="Статус отчета"
                    ),
                ),
                ("sort_level", models.IntegerField()),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "goal_name",
                    models.CharField(
                        max_length=50, verbose_name="Название цели"
                    ),
                ),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AmbassadorStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("assignment_date", models.DateField(verbose_name="Дата")),
                (
                    "ambassador_id",
                    models.ForeignKey(
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambassador.ambassador",
                        verbose_name="Амбассадор",
                    ),
                ),
                (
                    "ambassador_status_id",
                    models.ForeignKey(
                        max_length=50,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ambassador.ambassadorstatus",
                        verbose_name="Статус",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AmbassadorGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ambassador_id",
                    models.ForeignKey(
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambassador.ambassador",
                        verbose_name="Амбассадор",
                    ),
                ),
                (
                    "goal_id",
                    models.ForeignKey(
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambassador.goal",
                        verbose_name="Цель",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AmbassadorActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.ForeignKey(
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambassador.activity",
                        verbose_name="Активный",
                    ),
                ),
                (
                    "ambassador_id",
                    models.ForeignKey(
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambassador.ambassador",
                        verbose_name="Амбассадор",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AmbassadorAchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата выполнения"
                    ),
                ),
                (
                    "achive_id",
                    models.ForeignKey(
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambassador.achive",
                        verbose_name="Достижения",
                    ),
                ),
                (
                    "ambassador_id",
                    models.ForeignKey(
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambassador.ambassador",
                        verbose_name="Амбассадор",
                    ),
                ),
            ],
        ),
    ]
