# Generated by Django 4.2.7 on 2024-02-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ambassador", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambassadorachive",
            name="achive_id",
        ),
        migrations.RemoveField(
            model_name="ambassadorachive",
            name="ambassador_id",
        ),
        migrations.DeleteModel(
            name="Achive",
        ),
        migrations.DeleteModel(
            name="AmbassadorAchive",
        ),
    ]
