# Generated by Django 4.2.7 on 2024-03-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassador", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambassadorgoal",
            name="own_version",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Своя версия",
            ),
        ),
    ]
