# Generated by Django 4.2.7 on 2024-03-05 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telegram", "0002_alter_telegrambot_registration_date"),
        ("ambassador", "0003_ambassadorgoal_own_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                max_length=50,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="status",
            field=models.ForeignKey(
                max_length=50,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="ambassador.ambassadorstatus",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="telegram_bot",
            field=models.ForeignKey(
                max_length=50,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="telegram.telegrambot",
                verbose_name="Телеграмм бот",
            ),
        ),
        migrations.AlterField(
            model_name="ambassadoractivity",
            name="activity",
            field=models.ForeignKey(
                max_length=50,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ambassadors",
                to="ambassador.activity",
                verbose_name="Вид деятельности",
            ),
        ),
        migrations.AlterField(
            model_name="ambassadoractivity",
            name="ambassador",
            field=models.ForeignKey(
                max_length=50,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="ambassador.ambassador",
                verbose_name="Амбассадор",
            ),
        ),
        migrations.AlterField(
            model_name="ambassadorgoal",
            name="ambassador",
            field=models.ForeignKey(
                max_length=50,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="ambassador.ambassador",
                verbose_name="Амбассадор",
            ),
        ),
        migrations.AlterField(
            model_name="ambassadorgoal",
            name="goal",
            field=models.ForeignKey(
                max_length=50,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ambassadors",
                to="ambassador.goal",
                verbose_name="Цель",
            ),
        ),
        migrations.AlterField(
            model_name="ambassadorstatushistory",
            name="ambassador",
            field=models.ForeignKey(
                max_length=50,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="ambassador.ambassador",
                verbose_name="Амбассадор",
            ),
        ),
        migrations.AlterField(
            model_name="ambassadorstatushistory",
            name="ambassador_status",
            field=models.ForeignKey(
                max_length=50,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_history",
                to="ambassador.ambassadorstatus",
                verbose_name="Статус",
            ),
        ),
    ]
