# Generated by Django 4.2.7 on 2024-02-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassador", "0003_alter_ambassador_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="receipt_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Дата принятия в амбассадоры",
            ),
        ),
    ]
