# Generated by Django 4.2.7 on 2024-03-06 17:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0005_delete_ambassadorachieve"),
        ("ambassador", "0006_ambassador_activity_ambassador_goals_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmbassadorAchieve",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignment_date",
                    models.DateField(verbose_name="Дата получения ачивки"),
                ),
                (
                    "achieve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="achievements.achieve",
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ambassador.ambassador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ачивки амбассадоров",
                "verbose_name_plural": "Ачивки амбассадоров",
            },
        ),
        migrations.AddField(
            model_name="ambassador",
            name="achieves",
            field=models.ManyToManyField(
                blank=True,
                related_name="achieves",
                through="ambassador.AmbassadorAchieve",
                to="achievements.achieve",
            ),
        ),
    ]
