# Generated by Django 4.2.7 on 2024-03-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0003_delete_ambassadorprogram"),
        ("ambassador", "0007_ambassadorachieve_ambassador_achieves"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="address_country",
            field=models.CharField(max_length=50, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="address_settlement",
            field=models.CharField(
                max_length=50, verbose_name="Населённый пункт"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="email",
            field=models.EmailField(
                max_length=254, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="goals",
            field=models.ManyToManyField(
                related_name="goals",
                through="ambassador.AmbassadorGoal",
                to="ambassador.goal",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                null=True,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="programs",
            field=models.ManyToManyField(
                related_name="programs",
                through="ambassador.AmbassadorProgram",
                to="program.program",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="promocode",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Промокод"
            ),
        ),
    ]
