# Generated by Django 4.2.7 on 2024-02-28 16:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramBot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        max_length=100, verbose_name="Telegram chat ID"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        max_length=100, verbose_name="Telegram Username"
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата запуска бота пользователем",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
