# Generated by Django 4.2.7 on 2024-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambot",
            name="registration_date",
            field=models.DateTimeField(
                verbose_name="Дата запуска бота пользователем"
            ),
        ),
    ]
