name: Yandex ambassador CRM backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_backend_image_and_push_to_dockerhub:
    if: github.ref == 'refs/heads/master'
    name: Build docker backend image and push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push it
        uses: docker/build-push-action@v5
        with:
          context: ./bot
          push: true
          tags: ${{ secrets.DOCKER_REPO_USERNAME }}/yaambcrm_backend:latest

  deploy_to_server:
    name: Deploy project to server
    runs-on: ubuntu-latest
    needs:
      - build_backend_image_and_push_to_dockerhub

    steps:
      - uses: actions/checkout@v4

      - name: Make needs dir
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PHRASE }}
          script: mkdir -p /home/${{ secrets.SSH_USER }}/yaambcrm

      - name: Copy docker compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PHRASE }}
          source: "./infra/docker-compose-prod.yml"
          target: /home/${{ secrets.SSH_USER }}/yaambcrm/

      - name: Copy config files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PHRASE }}
          source: "./infra/nginx_conf/,./infra/cert/"
          target: /home/${{ secrets.SSH_USER }}/yaambcrm/

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PHRASE }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/yaambcrm/infra
            sudo docker compose --file ./docker-compose-prod.yml stop
            sudo docker compose --file ./docker-compose-prod.yml rm -f frontend
            sudo docker compose --file ./docker-compose-prod.yml rm -f backend
            sudo docker pull ${{ secrets.DOCKER_REPO_USERNAME }}/yaambcrm_backend:latest
            sudo docker pull asbest/am-crm-frontend:latest
            echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env
            echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> .env
            echo ENGINE=${{ secrets.ENGINE }} > .env
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
            echo DEBUG=${{ secrets.DEBUG }} >> .env
            echo USE_POSTGRES_DB=${{ secrets.USE_POSTGRES_DB }} >> .env
            echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> .env
            echo CSRF_TRUSTED_ORIGINS=${{ secrets.CSRF_TRUSTED_ORIGINS }} >> .env
            sudo docker compose --file ./docker-compose-prod.yml up -d